spring:
  application:
    name: bank-cards
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always

  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/card-db
    username: ${POSTGRES_USERNAME:admin}
    password: ${POSTGRES_PASSWORD:secret}

  liquibase:
    enabled: true
    change-log: classpath:/db/migration/db.changelog-master.yaml

springdoc:
  # don't generate responses from @ControllerAdvice
  override-with-generic-response: false

logging:
  level:
    org.springframework.security: WARN
    org.springframework.security.web.FilterChainProxy: WARN
    liquibase.precondition: WARN


jwt:
  secret: ${JWT_SECRET:3f7a9b2e5c8d1f6g4h0i9j2k5l7m8n1o3p6q9r2s4t7u0v1w5x8y2z}
  expiration: 86400000

encryptor:
  password: ${ENCRYPTOR_PASSWORD:g@#$%^&*()_ABCDEFG1234567890}
  salt: ${ENCRYPTOR_SALT:7342f2693f9c46d0}

app:
  admin:
    name: admin
    password: password
  hashEncoder:
    pepper: ${APP_HASHENCODER_PEPPER:5382h2673f4c47g0}
