spring:
  application:
    name: bank-cards
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always

  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/card-db
    username: admin
    password: secret

  security:
    user:
      name: bankUser
      password: password

  liquibase:
    enabled: true
    change-log: classpath:/db/migration/db.changelog-master.yaml

logging:
  level:
    org.springframework.security: DEBUG
#    org.springframework.web: DEBUG
    org.springframework.security.web.FilterChainProxy: DEBUG


jwt:
  secret: 3f7a9b2e5c8d1f6g4h0i9j2k5l7m8n1o3p6q9r2s4t7u0v1w5x8y2z
  expiration: 86400000

Что нужно сделать:
  - Указать настройки подключения к базе данных.
  - Указать порт приложения.
  - Настроить параметры безопасности и JWT.
  - Включить Swagger UI.
